@startuml
package "Diagrama de Clases" {
    class Persona {
        -id: Integer
        -disponibilidades: List<Disponibilidad>
    }

    class Disponibilidad {
        -id: Integer
    }

    Persona -->"*" Disponibilidad
}

package "Modelo de Datos" {
    entity "Persona" as persona {
        *id: int <<PK>>
    }

    entity "Disponibilidad" as disponibilidad {
        *id: int <<PK>>
        *prestador_id: int <<FK>>
    }

    persona ||--o{ disponibilidad
}
@enduml
