@startuml

package "Diagrama de Clases" {
    abstract class Reputacion {
        -id: Long
        -nombre: String
    }

    class ReputacionMala {
    -atributoDeMala: String
    }

    class ReputacionRegular {
    -atributoDeRegular:String
    }

    Reputacion <|-- ReputacionMala
    Reputacion <|-- ReputacionRegular
}

package "Modelo de Datos" as modelo {
    entity "Reputacion" as reputacion {
        +id: BigInt [PK]
        +nombre: varchar(255)
        +tipo: varchar(50)
        +atributoDeMala: varchar(255)
        +atributoDeRegular: varchar(255)
    }


}
@enduml

