@startuml
package "Diagrama de clases" {
    interface AlgoritmoRecomendacionOfertas {
        +recomendarOfertas(cliente: Cliente)
    }

    class AlgoritmoRecomendacionBasadoEnHistorial {
        +recomendarOfertas(cliente: Cliente)
    }

    class AlgoritmoRecomendacionBasadoEnPreferencias {
        +recomendarOfertas(cliente: Cliente)
    }

    AlgoritmoRecomendacionOfertas <|-- AlgoritmoRecomendacionBasadoEnHistorial
    AlgoritmoRecomendacionOfertas <|-- AlgoritmoRecomendacionBasadoEnPreferencias

    class Cliente {
        -Integer id;
        -algoritmoRecomendacion: AlgoritmoRecomendacionOfertas
    }

    Cliente --> AlgoritmoRecomendacionOfertas
}


package "Modelo de Datos" {
    entity "cliente" as cliente {
        +id: INT <PK>
        +nombre: VARCHAR(50)
        +algoritmoRecomendacion: VARCHAR(50)
    }

}
@enduml
